Multiplicación y división.
JoanBoters/ModGestion-paqueteR pull request #2
Opened 2021-01-10 21:18 UTC by JoanBoters

Se quiere añadir la multiplicación y la división,

2021-01-12 16:04 UTC, aalcacer requested changes

2021-01-12 16:04 UTC, aalcacer commented on R/div.R
> +#' div(5,3)
Añade más ejemplos :)

2021-01-12 16:04 UTC, aalcacer commented on R/mult.R
> +#' @seealso \link{div}
Añade un link a la suma

2021-01-13 09:18 UTC, JoanBoters commented on R/mult.R
> +#' @seealso \link{div}
Hecho!!
Me he liado un poco con el git pull y el push. Creo que se ha subido bien con las modificaciones. Creo que ahora le tengo que dar al re-request pero no lo tengo super claro, si me he equivocado en algo me dices.

2021-01-13 09:26 UTC, JoanBoters commented on R/div.R
> +#' div(5,3)
Hecho!

2021-01-15 16:44 UTC, aalcacer approved these changes
Ahora sí, ya puedes hacer el merge!

2021-01-15 16:47 UTC, merged